# Generated by Django 5.2.7 on 2025-11-06 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('data_cadastro', models.DateTimeField()),
                ('tipo_usuario', models.CharField(choices=[('G', 'gratuito'), ('P', 'premium')], default='G', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_interesse', models.CharField(max_length=100)),
                ('nivel_experiencia', models.CharField(choices=[('J', 'junior'), ('P', 'pleno'), ('S', 'senior')], default='j', max_length=1)),
                ('objetivo_pessoal', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='usuarios.usuario')),
            ],
        ),
    ]
