# Generated by Django 5.2.7 on 2025-11-20 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreiras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacao',
            name='atividade',
        ),
        migrations.AddField(
            model_name='atividade',
            name='recomendacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='carreiras.recomendacao'),
        ),
    ]
