# Generated by Django 5.2.7 on 2025-12-16 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreiras', '0002_remove_recomendacao_atividade_atividade_recomendacao'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacao',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil'),
        ),
    ]
